version: '3'

services:
  development:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PSSWD}
      POSTGRES_DB: rejane_db
    ports:
      - '5432:5432'
    volumes:
      - './postgres-data:/var/lib/postgresql/data'

  test:
    image: postgres:13
    restart: always
    container_name: e2e-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
